### ISSUE TITLE
好东西，正好要找这样的东西。能否提供一个在线地址

### ISSUE THREAD

**Issue by hongwei7458** [wangmaosheng/MsSystem-BPM-ServiceAndWebApps#1]
本地找搭的报错，说数据库连不上。
System.AggregateException
  HResult=0x80131500
  Message=An error occurred while writing to logger(s). (Unable to connect to any of the specified MySQL hosts.)
  Source=Microsoft.Extensions.Logging
  StackTrace:
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app)
   at MsSystem.Identity.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\MsSystem-BPM-ServiceAndWebApps-master\MsSystem-BPM-ServiceAndWebApps-master\src\Services\Identity\MsSystem.Identity\Startup.cs:line 45

内部异常 1:
MySqlException: Unable to connect to any of the specified MySQL hosts.

内部异常 2:
AggregateException: One or more errors occurred. (由于目标计算机积极拒绝，无法连接。 127.0.0.1:3306)

内部异常 3:
ExtendedSocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:3306

**Comment by Chenlh** [comment]
server=192.168.x.x;port=3316;database=mssystemlog;uid=root;pwd=root;SslMode=none;
